const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync('filter-utils.js', 'utf8');
const storage = new Map();
const localStorage = { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) };
const window = { localStorage, fetch: () => Promise.resolve(), alert: () => {} };
const document = { readyState: 'loading', addEventListener: () => {}, getElementById: () => null, createElement: () => ({ appendChild: () => {}, style: {} }), head: { appendChild: () => {} }, querySelector: () => null, querySelectorAll: () => [], body: {} };
const context = { window, document, localStorage, location: { pathname: '/unknown.html', href: 'http://localhost/' }, URL, URLSearchParams, Request: class Request {}, console };
vm.runInNewContext(code, context);
const saved = window.POSFilters.save('persistence', { preset: 'custom', from: '2026-08-01', to: '2026-08-23', limit: 100 });
if (saved.preset !== 'custom' || saved.limit !== 100 || storage.size !== 1) throw new Error('save failed');
const loaded = window.POSFilters.load('persistence', { preset: 'today', limit: 20 });
if (loaded.from !== '2026-08-01' || loaded.to !== '2026-08-23' || loaded.limit !== 100) throw new Error('load failed');
const cleared = window.POSFilters.clear('persistence', { preset: 'today', limit: 20 });
if (cleared.preset !== 'today' || cleared.limit !== 20 || storage.size !== 0) throw new Error('clear failed');
if (window.POSFilters.periodRange('all').from !== '' || window.POSFilters.periodRange('all').to !== '') throw new Error('all-period failed');
console.log('PASS filter persistence contract');
